OLED_ENABLE = yes
VIA_ENABLE = no
SPLIT_TRANSPORT = mirror
PIN_COMPATIBLE = elite_c

# Features
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
LEADER_ENABLE = yes
WAIT_FOR_USB = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
